spring:
  application:
    name: products-service
  liquibase:
    change-log: classpath:config-liquibase/master.yml
    enabled: true
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: sa
    password: sa
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
springdoc:
  swagger-ui:
    path: /docs